# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group <https://www.opalmedapps.com>
#
# SPDX-License-Identifier: MIT

# to test docker-build workflow in test workflow
FROM alpine:latest

RUN apk add --no-cache bash

ENTRYPOINT [ "/bin/bash" ]
